### ISSUE TITLE
Contributing Guidelines hinzufügen

### ISSUE THREAD

**Issue by JulianWgs** [dhueser/MDA-Vorlesung-iprom-tu-bs#4]
- Wie ist die Ordnerstruktur/ das Projekt aufgebaut?
- Wie ist das Vorgehen, wenn man einen Fehler findet oder etwas verbessern möchte?
- Was gehört in das Repository und was nicht?

Weiterführende Links:
- Tutorial: https://help.github.com/en/articles/setting-guidelines-for-repository-contributors
- Beispiel: https://github.com/tensorflow/tensorflow/blob/master/CONTRIBUTING.md

**Comment by dhueser** [comment]
Lieber Julian,
  mit einem Jahr Verspätung habe ich jetzt erst Deinen Vorschlag aufgenommen, diese Links vorne in die README zu legen. Ich habe jetzt auch auf Stud.IP geschrieben, dass die Studierenden gerne Vorschläge einbringen können, die sie per Email, oder als Nachricht in Stud.IP oder als Issue auf github schicken können. Wir Lehrenden müssen auch noch viel lernen hinsichtlich der Digitalisierung. Jetzt sitze ich nicht am iprom, sondern in Hamburg und werde von dort aus die Vorlesung via BigBlueButton halten. VG - doro

**Comment by JulianWgs** [comment]
Das freut mich sehr! Ich hoffe sehr, dass die Studierenden das Angebot annehmen und nicht dass das ganze Wissen in privaten Dropboxen gehortet wird und irgendwann verschwindet.

Viele Spaß bei der Vorlesung und liebe Grüße 
Julian
